name: Run Script

on:
  push:
    branches:
      - uwp  # Adjust the branch name as needed
  pull_request:
    branches:
      - uwp  # Adjust the branch name as needed

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: source your_environment_file.env  # Source the environment file

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Run script
      run: bash add_env_variables.sh  # Execute the bash script

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.VERCEL_TOKEN }}
