name: Update duckstation depends

on:
  push:
    branches:
      - uwp
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Extract 7z Archive
        run: |
          curl -L -o deps-x64.7z https://github.com/stenzek/duckstation-ext-qt-minimal/releases/download/latest/deps-x64.7z
          7z x deps-x64.7z -odep/msvc/* -r
          rm deps-x64.7z

      - name: Configure Git
        run: |
          git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Commit Changes
        run: |
         git add --all
         git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update depends"
      
      - name: Push Changes
        if: github.event_name == 'push'
        run: |
          git push origin ${{ github.ref }}
